sudo: false
language: node_js
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"
node_js:
  - '6'
  - '8'
script: npm run test
deploy:
  provider: npm
  email: mitmaro@gmail.com
  api_key:
    secure: TODO-ADD
  on:
    tags: true
    repo: MitMaro/eslint-config-mitmaro
    node: '8'
